### PR TITLE
fix: Some styling changes.

### PR DESCRIPTION
**Pull request by cherouvim**

### CODE REVIEW

**Review by jmike — APPROVED** [review]
💯 Thank you for paying attention to detail. Please proceed with merging.

**Comment by cherouvim** [comment]
> Please proceed with merging.

Can I do this myself? Not sure how.

**Comment by jmike** [comment]
I believe there should be a merge button below. Anyway, no worries. I shall do this.

**Comment by cherouvim** [comment]
I looked hard but couldn't find one. It makes sense though since I believe I am not a maintainer of this repo.

**Pull request merged**
